version: '3.7'

services:
  acme:
    # build:
    #   context: ..
    image: whatwewant/acme:v0.0.3
    env_file:
      - /tmp/.env
    # environment:
    #   DEBUG: 'true'
    volumes:
      - /tmp/data/ssl:/data/ssl
      # - /tmp/data/acme:/root/.acme.sh